### ISSUE TITLE
User Modifies Template Questions After Link is Being Sent

### ISSUE THREAD

**Issue by andyzhou1999** [andyzhou1999/csci-401-capstone#1]
System should automatically update the questionnaire after modification. If the template is deleted, the link should not cause any crashes or exception

**Comment by andyzhou1999** [comment]
After testing, delete or modifying a template after link is sent will not cause crash or change the questions that student will receive. But it should allow updates to the questionnaire, instead of sticking to the original questions.

**Comment by jaredk10** [comment]
Will leave implementation as is for now. See issue #15
