### ISSUE TITLE
Issues with parsing "Tag" in questionnaire template editing page

### ISSUE THREAD

**Issue by FrostXTJ** [andyzhou1999/csci-401-capstone#12]
1. The user has to save the template before he can use the tags that is just created in the letter boilerplate, which is not intuitive. Usually, the user finishes all his edits and then saves the template.

For example: Tag <!MAJOR> is created, but it cannot been in the letter boilerplate section until the user saves the template first.
![image](https://user-images.githubusercontent.com/41350819/134303050-1d5d48fd-befa-4768-97a2-99423b1b0812.png)

2. Errors in parsing tags if the tag is not formatted in `<!TAG_NAME>`. However, there is no warning messages or any cues that prevent users from naming it in the wrong way. In addition, the default placeholder gives a wrong clue. 

![Screen Shot 2021-09-22 at 12 48 29 AM](https://user-images.githubusercontent.com/41350819/134303725-d61eec69-b3a5-4af8-baa8-536427161490.png)

The placeholder should be something like `tag (e.g. <!fname>` instead of `#fname`.
![image](https://user-images.githubusercontent.com/41350819/134304062-b0b90d65-3c39-402a-abe6-92d0906a6405.png)

**Comment by andyzhou1999** [comment]
Also, it user makes a tag like <!!!!<!!!!!Major>, it also cause problem
