### ISSUE TITLE
Issue with the template editor: removing added custom question doesnt disappear without refreshing the page

### ISSUE THREAD

**Issue by andrewhan324** [andyzhou1999/csci-401-capstone#13]
If the user adds a custom question and then deletes the question, it doesn't disappear without refreshing the page

![Screen Shot 2021-09-22 at 12 58 25 AM](https://user-images.githubusercontent.com/52876365/134305132-80d82c29-6430-436d-ae54-f62764bd264d.png)

![Screen Shot 2021-09-22 at 12 58 30 AM](https://user-images.githubusercontent.com/52876365/134305269-aca47529-9895-49cd-9084-e06772caecea.png)

![Screen Shot 2021-09-22 at 12 58 25 AM](https://user-images.githubusercontent.com/52876365/134305310-9bdab80b-1655-4464-a551-bc3d573f6814.png)

**Comment by andyzhou1999** [comment]
Currently, the ejs files for this pages does not provide UI to adding custom questions. The add custom question function is incomplete and needs a little bit more work.

**Comment by andyzhou1999** [comment]
We will only allow 3 types of question. No more custom questions. Make life easier for users.
